accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login_form_view, name="login"),
    path('register/', views.register_view, name="register"),
    path('otp/', views.otp_message_view, name="otp"),
    path("resend/", views.resend_message, name="resend"),
    path('logout/', views.logout_view, name="logout"),
    path('reset-password/', views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_sent/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

items/urls.py
from django.urls import path
from . import views


app_name = "items"
urlpatterns = [
    path("cart/", views.cart_customer_view, name="cart"),
    path('add-to-cart/', views.add_to_cart_view, name="add_to_cart")
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls", namespace="products")),
    path('', include("items.urls", namespace="items")),
    path('account/', include("accounts.urls", namespace="accounts"))
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.utils.text import slugify
import random
import string
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
# Create your models here.


User_Model = settings.AUTH_USER_MODEL

Gender_Choices = (
    ("Male", "Male"),
    ("Female", "Female")
)
class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username = username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(
            email,
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_verified = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email               = models.EmailField(verbose_name='email address'.title(),max_length=255,unique=True)
    username            = models.CharField(max_length=250, unique=True, verbose_name="username".title())
    full_name           = models.CharField(max_length=350, verbose_name="your full name".title(), blank=True)
    date_of_birth       = models.DateField(blank=True, null=True,)
    avatar              = models.ImageField(default="avatars/images.jpeg", upload_to="avatars")
    bio                 = models.CharField(max_length=500, blank=True)
    gender              = models.CharField(choices=Gender_Choices, blank=True, max_length=12)
    country             = models.CharField(blank=True, null=True, max_length=200)
    phone_number        = models.CharField(max_length=30, blank=True)
    is_admin            = models.BooleanField(default=False)
    followers           = models.ManyToManyField(User_Model, blank=True)
    website             = models.URLField(blank=True, null=True, max_length=200)
    facebook_profile    = models.URLField(blank=True, null=True, max_length=200)
    is_verified         = models.BooleanField(default=False)
    is_active           = models.BooleanField(default=True)
    tow_factor          = models.BooleanField(default=False)
    timestamp           = models.DateTimeField(auto_now_add=True)
    updated             = models.DateTimeField(auto_now=True)
    objects             = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, PasswordResetForm,SetPasswordForm
from django.core.exceptions import ValidationError

from .models import User


class CustomSetPasswordForm(SetPasswordForm) :
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].label = ''
        self.fields['new_password2'].label = ''
        self.fields['new_password1'].help_text = ''
        self.fields['new_password1'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"New Password", 'data-toggle': 'password'})
        self.fields['new_password2'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"New Password Confirmation", 'data-toggle': 'password'})
        
   




class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label='Email', max_length=254, widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class': 'form-control', 'placeholder': 'Enter your Email Address'}))



class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','username')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        if len(password2) > 8 :
            forms.ValidationError('please pick password more than 8')
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()

        return user
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['username'].label = ''
        self.fields['password1'].label = ''
        self.fields['email'].label = ''
        self.fields['username'].label = ''
        self.fields['password2'].label = ''
        # self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        # self.fields['username'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"Username"})
        self.fields['password1'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"Password", "data-toggle":"password"})
        self.fields['password2'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"Password confirmation", 'data-toggle': 'password'})
        self.fields['email'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"Email"})
        self.fields['username'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"Username"})


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'username', 'is_active', 'is_admin')


class LoginForm(forms.Form) :
    username = forms.CharField(label="E-mail", widget=forms.EmailInput)
    password = forms.CharField(label="password", widget=forms.PasswordInput)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = ''
        self.fields['password'].label = ''
        self.fields['password'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"Password", 'data-toggle': 'password'})
        self.fields['username'].widget.attrs.update({'class':"form-control","id":"exampleInputEmail1","placeholder":"Your Email"})
        
   

class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label="Email", max_length=254, widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("There is no user registered with the specified email address!")
        return email

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User
from django.contrib import messages
from django.contrib.auth import login , logout, authenticate
from .forms import UserCreationForm, LoginForm, CustomPasswordResetForm,CustomSetPasswordForm
from .utils import send_otp
from datetime import datetime
import pyotp
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.views import PasswordResetConfirmView


# Create your views here.

from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView


class PasswordResetView(FormView):
    form_class = CustomPasswordResetForm
    template_name = 'accounts/password_reset.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'
    subject_template_name = 'accounts/password_reset_subject.txt'
    def form_valid(self, form):
        form.save(
            domain_override='example.com',
            use_https=self.request.is_secure(),
            email_template_name=self.email_template_name,
            request=self.request,
        )
        messages.success(self.request, 'Password reset email has been sent.')
        return super().form_valid(form)


class PasswordResetDoneView(TemplateView):
    template_name = 'accounts/password_reset_done.html'







class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')
    form_class = CustomSetPasswordForm


class PasswordResetCompleteView(TemplateView):
    template_name = 'accounts/password_reset_complete.html'













def login_form_view(request) :
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid() :
            username = request.POST.get("username")
            password = request.POST.get("password")
            print(username)
            user = authenticate(request, username=username, password=password)
            if user is not None :
                login(request, user)
                return redirect("products:home")
            else :
                messages.error(request, "email or password is wrong")
    else :
        form = LoginForm()
    context = {
        "l_form" : form
    }
    return render(request, "accounts/authentications.html", context)


def register_view(request) :
    template_name = "accounts/authentications.html"
    form = UserCreationForm(request.POST or None)
    if form.is_valid() :
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        email = user.email
        request.session["email"] = email
        request.session["username"] = user.username
        send_otp(request)
        return redirect("accounts:otp")   
    context = {
        "r_form" : form
    }
    return render(request, template_name, context)


def otp_message_view(request) :
    email = request.session.get("email")
    if email :
        erorr_message = None
        if request.method == "POST" :
            otp = request.POST.get("otp")
            email = request.session["email"]
            otp_secret_key = request.session["otp_secret_key"]
            otp_valid_date = request.session["otp_valid_date"]
            if otp_secret_key and otp_valid_date:
                valid_date = datetime.fromisoformat(otp_valid_date)
                if valid_date > datetime.now() :
                    totp = pyotp.TOTP(otp_secret_key, interval=300)
                    if totp.verify(otp) :
                        user = get_object_or_404(User, email=email)
                        user.is_active = True
                        user.is_verified = True
                        user.save()
                        login(request, user)
                        del request.session["otp_valid_date"]
                        del request.session["otp_secret_key"]
                        del request.session["email"]
                        del request.session["username"]
                        return redirect("/")
                    else :
                        erorr_message = "invalid your one time password".title()
                else :
                    erorr_message = "one time password has expired".title()
            else :
                erorr_message = "ups...something went wrong :(".capitalize()
    else :
        return redirect("products:not_found")
    context = {
        "erorr_message" : erorr_message
    }
    return render(request, "accounts/otp.html", context)


def resend_message(request) :
    email = request.session["email"]
    if email :
        if request.method == "GET" :
            resend = request.GET.get("resend")
            send_otp(request)
            return redirect(request.META.get('HTTP_REFERER'))
    else :
        return redirect("products:not_found")

def logout_view(request) :
    template_name = "accounts/logout.html"
    if request.method == "POST" :
        logout(request)
        return redirect("accounts:login")
    context = {
        "logout":f"{str(request.user.username).upper()}"
    }
    return render(request, template_name, context)

accounts/templates/accounts/authentications.html
{% extends 'base.html' %}


{% block title %}
    
    {% if l_form %}
        login
    {% elif r_form %}
        register
    {% else %}
        logout {{request.user.username}}
    {% endif %}
        
{% endblock title %}
    


{% block content %}
    <div class="container mt-5">
        
        {% if messages %}
        
        {% for message in messages %}
            <p>
                {{message}}
            </p>
        {% endfor %}
            
            
        {% endif %}
{% if not request.user.is_authenticated  %}
<form action="" method="post">
{% csrf_token %}
    {% if l_form %}
    {{l_form.as_p}}
    <button type="submit" class="btn btn-primary">login</button>
    <small>
        Need account? <a href="{% url 'accounts:register' %}">Sign Up</a>
    </small>
    <br>
    <small>
         <a href="{% url 'accounts:password_reset' %}">forget password?</a>
    </small>
    {% elif r_form %}
    {{r_form.as_p}}
    <button type="submit" class="btn btn-primary">Register</button>
    <small>
        have account? <a href="{% url 'accounts:login' %}">Sign in</a>
    </small>
    {% endif %}
</form>
{% else %}
<p>
    already you are logged in {{request.user.username}} <a href="{% url 'accounts:logout' %}">logout</a>
</p>
{% endif %}
    </div>
{% endblock content %}
    

accounts/templates/accounts/logout.html
{% extends 'base.html' %}


{% block title %}
    logout {{request.user.username}}
{% endblock title %}
    


{% block content %}

{% if request.user.is_authenticated %}
<div class="container mt-5">
    <form action="." method="post">
        {% csrf_token %}
        <p>
            are you sure you want to logout ? {{logout}}
        </p>
        <button type="submit">yes</button>
    </form>
    {% else %}
<p class="container">
    you are not login in please <a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-primary">Sign In</button></a>  

    
    <a href="{%  url 'accounts:register' %}"><button type="button" class="btn btn-success">Sign Up</button></a>
</p>
{% endif %}
</div>

    
{% endblock content %}
    

accounts/templates/accounts/otp.html
{% extends 'base.html' %}


{% block title %}
    verfiy
{% endblock title %}
    


{% block content %}
    <div class="container mt-5">
        <p>
            Check your email We have sent you a verification email
        </p>
        {% if erorr_message %}
        <p>
            {{erorr_message}}
        </p>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="otp" id="">
            <button type="submit">confirm</button>
        </form>
         
        <form action="{% url 'accounts:resend' %}" method="get" name="name_form">
            {% csrf_token %}
            <input type="hidden" name="resend" value="resend">

            If you do not receive the confirmation message, click here <button type="submit">resend</button>
        </form>
    </div>
{% endblock content %}
    

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}


{% block title %}
    reset password
{% endblock title %}

{% block content %}
<div class="container">
<h1>Reset Password</h1>
{% if form.errors %}
<p class="alert alert-danger">Please correct the errors below.</p>
{% endif %}

    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
    </form>
</div>
    

{% endblock %}

    

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}


{% block title %}
    complate
{% endblock title %}
    

{% block content %}
<div class="container mt-5">
    <p>
        your password reset is done <a href="{% url 'accounts:login' %}">login</a>
    </p>
</div>
{% endblock content %}
    

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}


{% block title %}
    password confirm
{% endblock title %}
    


{% block content %}
<div class="container mt-5">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">confirm</button>
    </form>
</div>
{% endblock content %}
    

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}


{% block title %}
    password reset done
{% endblock title %}

{% block content %}
<p class="container">An email has been sent to your account with instructions on how to reset your password.</p>

{% endblock content %}
    

accounts/templates/accounts/password_reset_email.html
Hello {{ user.username }},

You have requested to reset your password for es store.

Please click the link below to reset your password:

http://127.0.0.1:8000/{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

Thank you,
The es store team



<!-- {% autoescape off %}
Hello {{ user.username }},

You have requested to reset your password for {{ site_name }}.

Please click the link below to reset your password:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

Thank you,
The {{ site_name }} team
{% endautoescape %} -->