items/urls.py
from django.urls import path
from . import views


app_name = "items"
urlpatterns = [
    path("cart/", views.cart_customer_view, name="cart"),
    path('add-to-cart/', views.add_to_cart_view, name="add_to_cart")
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls", namespace="products")),
    path('', include("items.urls", namespace="items")),
    path('account/', include("accounts.urls", namespace="accounts"))
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="mt-3">
        {% include 'navbar.html' %}
    </div>
    <div>
        {% block content %}
            
        {% endblock content %}
    </div>
    <script src="/static/action/master.js" defer></script>
    {% block script %}
        
    {% endblock script %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
   
  </body>
</html>

templates/footer.html
<!--  New section -->
<div class="py-5 px-3">
    <div class="container py-5">
      <h3 class="fw-bold  text-center text-md-start mb-3">Why choose Us?</h3>
      <div class="row">
          
      <div class="col-lg-4 col-md-6 d-flex align-items-center">
     
        <div class="bg-white shadow-sm rounded-circle p-3">
        <i class="fa-solid fa-money-bill fs-1 text-primary"></i>
      </div>
        
        <div class="ms-3 mt-md-5">
          <h6 class="h6 fw-bold">Reasonable prices</h6>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
        </div>
      </div>
             
          
      <div class="col-lg-4 col-md-6 d-flex align-items-center">
     
        <div class="bg-white shadow-sm rounded-circle p-3">
        <i class="fa-solid fa-star  fs-1 text-primary"></i>
      </div>
        
        <div class="ms-3 mt-md-5">
          <h6 class="h6 fw-bold">
    Best quality</h6>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
        </div>
      </div>
        
          
      <div class=" col-lg-4 col-md-6 d-flex align-items-center">
     
        <div class="bg-white shadow-sm rounded-circle p-3">
       <i class="fa-solid fa-plane  fs-1 text-primary"></i>
      </div>
        <div class="ms-3 mt-md-5">
          <h6 class="h6 fw-bold">Worldwide shipping</h6>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
        </div>
      </div>
          
          
      <div class="col-lg-4 col-md-6 d-flex align-items-center">
     
        <div class="bg-white shadow-sm rounded-circle p-3">
       <i class="fa-solid fa-users  fs-1 text-primary"></i>
      </div>
        <div class="ms-3 mt-md-5">
          <h6 class="h6 fw-bold">Customer satisfaction</h6>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
        </div>
      </div>
         
          
      <div class="col-lg-4 col-md-6 d-flex align-items-center">
     
        <div class="bg-white shadow-sm rounded-circle p-3">
     <i class="fa-solid fa-thumbs-up  fs-1 text-primary"></i>
      </div>
        <div class="ms-3 mt-md-5">
          <h6 class="h6 fw-bold">Happy customers</h6>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
        </div>
      </div>
       
        <div class="col-lg-4 col-md-6 d-flex align-items-center">
     
        <div class="bg-white shadow-sm rounded-circle p-3">
     <i class="fa-solid fa-box-open fs-1 text-primary"></i>
      </div>
        <div class="ms-3 mt-md-5">
          <h6 class="h6 fw-bold">Thousand items</h6>
          <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmor</p>
        </div>
      </div>
        
      
      </div><!--row idv--->
      
    </div>
    </div>
    
    
    <!--new section---->
    <div class="pb-5">
      <div class="container py-5">
        <h3 class="h3 fw-bold mb-3 text-center text-md-start mb-3">Blog posts</h3>
       <div class="row mt-md-5">
         
         <div class="col-sm-6 col-md-6 col-lg-3">
           <img class="bg rounded" src="https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/posts/1.jpg" width="250" height="200"  </img>
           <div class="mt-3">
             <a href="#"  class="fw-bold">How to promote brands</a>
             <p class="text-muted">When you enter into any new area of science, you almost reach</p>
           </div>
         </div><!--col div -->
         
          <div class="col-sm-6 col-md-6 col-lg-3">
           <img class="bg rounded" src="https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/posts/2.jpg" width="250" height="200"  </img>
           <div class="mt-3">
             <a class="fw-bold">How we handle shipping</a>
             <p class="text-muted">When you enter into any new area of science, you almost reach</p>
           </div>
         </div><!--col div -->
         
          <div class="col-sm-6 col-md-6 col-lg-3">
           <img class="bg rounded" src="https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/posts/3.jpg" width="250" height="200"  </img>
           <div class="mt-3">
             <a class="fw-bold">How to promote brands</a>
             <p class="text-muted">When you enter into any new area of science, you almost reach</p>
           </div>
         </div><!--col div -->
         
          <div class="col-sm-6 col-md-6 col-lg-3">
           <img class="bg rounded" src="https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/posts/4.jpg" width="250" height="200"  </img>
           <div class="mt-3">
             <a class="fw-bold">Success story of sellers</a>
             <p class="text-muted">When you enter into any new area of science, you almost reach</p>
           </div>
         </div><!--col div -->
         
        </div><!-- div row -->
        
      </div>
    </div>
    
    
    <!-- Footer -->
    
    <div class="py-5">
      <div class="container">
        
      <div class="row d-flex">
        
        <div class="col-md-12 col-lg-3 mb-3">
       
        <img src="https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/logo.svg"></img>
        <p class="mt-4 text-muted">© 2018- 2021 Templatemount.<br>
    All rights reserved.</p>
    
        </div>
        
        <div class="col-6 col-sm-6 col-md-4 col-lg-2">
            
          <h6 class="h6 fw-bold">Store</h6>
    
            <a 
               href="#" class="text-decoration-none text-muted">About us</a>
           <a 
              href="#" class="text-decoration-none text-muted">Find stories</a>
           <a 
              href="#" class="text-decoration-none text-muted">Categories</a>
           <a 
              href="#" class="text-decoration-none text-muted">Blogs</a>
        </div>
        
        <div class="col-6 col-sm-6 col-md-4 col-lg-2">
          <h6 class="h6 fw-bold">Information</h6>
          <a href="#" class="text-decoration-none text-muted">About us</a>
           <a href="#" class="text-decoration-none text-muted">Find stories</a>
           <a href="#" class="text-decoration-none text-muted">Categories</a>
           <a href="#" class="text-decoration-none text-muted">Blogs</a>
        </div>
        
        <div class="col-6 col-sm-6 col-md-4 col-lg-2 mt-3 mt-md-0">
          <h6 class="h6 fw-bold">Support</h6>
          <a href="#" class="text-decoration-none text-muted">About us</a>
           <a href="#" class="text-decoration-none text-muted">Find stories</a>
           <a href="#" class="text-decoration-none text-muted">Categories</a>
           <a href="#" class="text-decoration-none text-muted">Blogs</a>
        </div>
        
        <div class="col-lg-3 mt-3 mt-lg-0">
     
          <h6 class="h6 fw-bold">Newsletter</h6>
          <p class="text-muted">Stay in touch with latest updates about our products and offers</p>
     
          <div class="input-group">
      <input type="text" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-secondary" type="button">Join</button>
      </div>
    </div>
        </div>
    
        
        
      </div><!--row div-->
      
      
      
      </div>
    </div>
        
        
        
        
        
        
        
        
        

templates/navbar.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"></script>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"rel="stylesheet"/>

<!--Font awesome!-->
<script src="https://kit.fontawesome.com/f4e855eb8f.js" crossorigin="anonymous"></script>


<div class="container pt-3">

  <div class="input-group">
     <a class="navbar-brand" href="#"> <img class="me-3 me-md-5" src="https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/logo.svg"></img></a> <!--LOGO!-->
  
  <input type="text" id="input-form" class="form-control" placeholder="Search" aria-label="Text input with dropdown button">
  <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">All type</button>
  <button class="btn btn-primary d-none d-lg-block"><i class="fa-solid fa-magnifying-glass rounded d-none d-lg-block"></i></button>
 
  <div class="ms-md-5 mt-2 mt-md-0">
    <a type="button" class="btn btn-outline-primary fw-500 rounded ">
      <i class="fa-solid fa-user me-lg-2"></i><p class="d-none d-lg-inline">Sign in</p>
    </a>
    <a type="button" class="btn btn-outline-primary fw-500 rounded">
      <i class="fa-solid fa-heart me-lg-2"></i><p class="d-none d-lg-inline">Wishlist</p>
    </a>
    <a href="{% url 'items:cart' %}" type="button" class="btn btn-outline-primary fw-500 rounded ">
      <i class="fa-solid fa-cart-shopping me-lg-2"></i><p class="d-none d-lg-inline">My Cart</p>
     
    </a>
    </div>
  
  <ul class="dropdown-menu  dropdown-menu-start">
    <li><a class="dropdown-item" href="#">Best</a></li>
    <li><a class="dropdown-item" href="#">Special</a></li>
    <li><a class="dropdown-item" href="#">Latest</a></li>  
  </ul>
  
</div>

</div> <!--Container div!-->
<hr>


<!--  Navbar  -->
<div class="container mt-3">
  <nav class="navbar navbar-expand-lg navbar-light">
  
    <button class="navbar-toggler mb-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Hot offers</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">Gift boxes</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">Projects</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">Menu item</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#">Menu name</a>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Others
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
</div>
    </div>

    
    <!--   Product section   -->
    
 