items/urls.py
from django.urls import path
from . import views


app_name = "items"
urlpatterns = [
    path("cart/", views.cart_customer_view, name="cart"),
    path('add-to-cart/', views.add_to_cart_view, name="add_to_cart")
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls", namespace="products")),
    path('', include("items.urls", namespace="items")),
    path('account/', include("accounts.urls", namespace="accounts"))
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path('', views.home_product, name="home"),
    path('upload/product/',views.upload_product_view, name="upload"),
    path('manage/product/<slug>/', views.product_manage_detil, name="manage"),
    path('delete-image/<pk>/', views.delete_image_view, name="delete_image"),
    path('upload-image/<pk>/', views.upload_image, name="upload_image"),
    path('not-found/', views.not_found_page, name="not_found"),
    path('detail-product/<slug>/', views.detail_product_view, name="detail_product")
]

products/models.py
from django.db import models
from accounts.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
# Create your models here.

def slugify(str):
    str = str.replace(" ", "-")
    str = str.replace(",", "-")
    str = str.replace("(", "-")
    str = str.replace(")", "")
    str = str.replace("؟", "")
    return str

class Category(models.Model) :
    name = models.CharField(max_length=300, unique=True)
    slug = models.SlugField(blank=True, null=True, unique=True)

    def __str__(self) :
        return self.name
    
    def save(self, *args, **kwargs) :
        if not self.slug :
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)
    
class Brand(models.Model) :
    name = models.CharField(max_length=300, unique=True)
    slug = models.SlugField(blank=True, null=True, unique=True)
    
    def __str__(self) :
        return self.name
    def save(self, *args, **kwargs) :
        if not self.slug :
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)
    


class Product(models.Model) :
    salesman            = models.ForeignKey(User, on_delete=models.CASCADE)
    name                = models.CharField(max_length=100)
    slug                = models.SlugField(blank=True, null=True, unique=True)
    price               = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)
    category_sex        = models.CharField(max_length=10, blank=True)
    category            = models.ForeignKey(Category, blank=True,null=True, on_delete=models.SET_NULL)
    brand               = models.ForeignKey(Brand, blank=True,null=True, on_delete=models.SET_NULL)
    discound            = models.IntegerField(blank=True, null=True,
                                               validators=[MinValueValidator(0),
                                                            MaxValueValidator(100)])
    description         = models.TextField()
    timestamp           = models.DateTimeField(auto_now_add=True)
    updated             = models.DateTimeField(auto_now=True)


    @property
    def new_price_after_discound(self) :
        if self.discound  :
            new_price = self.price - self.price * self.discound / 100
        else :
            new_price = self.price
        return new_price

    def __str__(self) :
        return f"{str(self.name)} {self.new_price_after_discound}"
    
    def manager_url(self) :
        return reverse("products:manage", kwargs={"slug":self.slug})
    
    def upload_image_url(self) :
        return reverse("products:upload_image",kwargs={"pk":self.pk})
    
    def detail_product_url(self) :
        return reverse("products:detail_product", kwargs={"slug":self.slug})
    
    @property
    def all_image_related(self) :
        return self.images_set.all()
    @property
    def first_image(self) :
        try :
            image = self.all_image_related.first()
        except :
            image = None
        return image
        
    @property
    def get_productpttachment(self) :
        return self.productattachment_set.all()

def get_image_filename(instance, filename):
    title = instance.product.name
    slug = slugify(title)
    return "product_images/%s-%s" % (slug, filename)  

class Images(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename,
                              verbose_name='Image')
    def __str__(self) :
        return f"iamge for product name {self.product.name} ID '{self.product.id}'"

    def delete_image_url(self) :
        return reverse("products:delete_image", kwargs={"pk": self.pk})
    
    


class ProductAttachment(models.Model):
    product             = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    size_number         = models.CharField(blank=True, null=True, max_length=100)
    size                = models.CharField(blank=True, null=True, max_length=100)
    color               = models.CharField(max_length=100, blank=True, null=True)
    inventory_quantity  = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    is_available        = models.BooleanField(default=False)
    active              = models.BooleanField(default=True)
    timestamp           = models.DateTimeField(auto_now_add=True)
    updated             = models.DateTimeField(auto_now=True)
    def __str__(self) :
        return f"iamge for product name {self.product.name} ID '{self.product.id}'"
    
    

products/forms.py
from django import forms
from django.forms import modelformset_factory, inlineformset_factory
from .models import *



input_css_class = "form-control"


class ProductForm(forms.ModelForm) :
    class Meta :
        model = Product
        fields = (       
            "name", "price" , "brand" , "category", "category_sex", "discound", "description" ,)
        widgets = {
                'description': forms.Textarea(attrs=({"rows":"4","cols":"20"}))
            }
class ImageForm(forms.ModelForm) :
    class Meta :
        model = Images
        fields = (
            "image",
        )
        widgets = {
                'image': forms.ClearableFileInput(attrs={'multiple': True})
            }
        

class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (       
            "name", "price" , "brand" , "category", "category_sex", "discound", "description" ,)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['name'].widget.attrs['placeholder'] = "Your name"
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = input_css_class
class ImageUpdateForm(forms.ModelForm) :
    class Meta :
        model = Images
        fields = (
            "image",
        )
        widgets = {
                'image': forms.ClearableFileInput(attrs={'multiple': True})
            }
        
class ProductAttachmentForm(forms.ModelForm):
    class Meta:
        model = ProductAttachment
        fields = [          
            "inventory_quantity",
            "size_number",
            "size",
            "active",
            "is_available"

        ]
        
    def clean_inventory_quantity(self) :
        inventory_quantity = self.cleaned_data.get("inventory_quantity")
        if inventory_quantity < 0 :
            forms.ValidationError("you inventory quantity is not valid")
        return inventory_quantity
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            if field in ['is_free', 'active']:
                continue
            self.fields[field].widget.attrs['class'] = input_css_class

ProductAttachmentModelFormSet = modelformset_factory(
    ProductAttachment,
    form=ProductAttachmentForm,
    fields = ["inventory_quantity", "size_number", "size", "color", "active"],
    extra=0,
    can_delete=True
)

ProductAttachmentInlineFormSet = inlineformset_factory(
    Product,
    ProductAttachment,
    form = ProductAttachmentForm,
    formset = ProductAttachmentModelFormSet,
    fields = ["inventory_quantity", "size_number", "color", "size", "active"],
    extra=0,
    can_delete=True
)

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import modelform_factory
from django.http import HttpResponseBadRequest, Http404, HttpResponse
from django.contrib import messages
from accounts.models import User
from .models import *
from .forms import *
# Create your views here.

def home_product(request) :
    qs = Product.objects.all()
    context = {
        "qs" : qs
    }
    return render(request, 'products/home.html', context)

def not_found_page(request) :
    return render(request, "products/not-found.html", {})



def upload_product_view(request) :
    template_name = "products/create-update.html"
    context = {}
    ImageFormSet = modelform_factory(Images, form=ImageForm)
    if request.method == 'POST':
        form_product = ProductForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES)
        if form_product.is_valid() and formset.is_valid() :
            obj = form_product.save(commit=False)
            if request.user.is_authenticated:
                obj.salesman = request.user
                obj.save()
                for image in request.FILES.getlist('image') :
                    Images.objects.create(product=obj, image=image)
                return redirect(obj.manager_url())
            form_product.add_error(None, "Your must be logged in to create products.")
        else :
            print(form_product.errors, formset.errors)
    else :
        form_product = ProductForm()
        formset = ImageFormSet()
    context["form_image"] = formset
    context["form_product"] = form_product
    return render(request, template_name, context)


def product_manage_detil(request, slug) :
    template_name = 'products/manager.html'
    obj = get_object_or_404(Product, slug=slug)
    attachments = ProductAttachment.objects.filter(product=obj)
    is_manager = False
    if request.user.is_authenticated:
        is_manager = obj.salesman == request.user
    context = {"object": obj}
    if not is_manager:
        return HttpResponseBadRequest()
    form = ProductUpdateForm(request.POST or None, instance=obj)
    formset = ProductAttachmentInlineFormSet(request.POST or None, queryset=attachments)
    if form.is_valid() and formset.is_valid():
        instance = form.save(commit=False)
        instance.save()
        formset.save(commit=False)
        for _form in formset:
            is_delete = _form.cleaned_data.get("DELETE")
            try:
                attachment_obj = _form.save(commit=False)
            except:
                attachment_obj = None
            if is_delete:
                if attachment_obj is not None:
                    if attachment_obj.pk:
                        attachment_obj.delete()
            else:
                if attachment_obj is not None:
                    attachment_obj.product  = instance
                    attachment_obj.save()
        if not obj.all_image_related :
            return redirect(obj.upload_image_url())
        return redirect(obj.manager_url())
    context['form'] = form
    context['formset'] = formset
    return render(request, template_name, context)

def delete_image_view(request, pk) :
    try :
        item = Images.objects.get(pk=pk)
    except Images.DoesNotExist :
        raise Http404
    if request.user.is_authenticated :
        if request.user == item.product.salesman :
            item.delete()
            return redirect(item.product.manager_url())
    return HttpResponseBadRequest()
    
def upload_image(request, pk) :
    template_name = "products/images.html"
    context = {}
    ImageFormSet = modelform_factory(Images, form=ImageForm)
    if request.user.is_authenticated :
        try :
            obj = Product.objects.get(pk=pk)
        except Product.DoesNotExist :
            raise Http404
        form = ImageFormSet(request.POST or None, request.FILES or None) 
        if form.is_valid() :
            for image in request.FILES.getlist('image') :
                    Images.objects.create(product=obj, image=image)
            return redirect(obj.manager_url())
        context["form"] = form
    else :
        return HttpResponseBadRequest()
    return render(request, template_name, context)
    

def detail_product_view(request, slug=None) :
    template_name = "products/detail.html"
    context = dict()
    if slug :
        try :
            qs = Product.objects.get(slug=slug)
            product = ProductAttachment.objects.filter(product=qs)
            context["qs"] = qs
            context["product"] = product
        except Product.DoesNotExist :
            return redirect("products:not_found")
        if qs.brand :
            similar_brand = Product.objects.filter(brand__name=qs.brand.name).order_by("?")[:4]
            context["s_brand"] = similar_brand
        if qs.category :
            similar_c = Product.objects.filter(category__name=qs.category.name).order_by("?")[:4]
            context["s_category"] = similar_c
    else :
        return redirect("products:home")
    return render(request, template_name, context)
        

products/templates/products/create-update.html
{% extends 'base.html' %}


{% block title %}
    upload
{% endblock title %}
    


{% block content %}
<div class="container mt-5">
    <form action="." method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{form_image.as_p}}
            {{form_product.as_p}}
            <button type="submit">Upload now</button>
        </form>
    </div>
{% endblock content %}
    

products/templates/products/detail.html
{% extends 'base.html' %}


{% block title %}
    {{qs.name}}
{% endblock title %}
    


{% block content %}



<!-- {% for item in product %}

{% if item.size %}
<p>
    {{item.size}}
</p>
{% endif %}
{% endfor %}
    




{% for item in product %}
{% if item.color %}
    <p>
        {{item.color}}
    </p>
{% endif %}  
{% endfor %}


{% for item in product %}
{% if item.size_number %}
    <p>
        {{item.size_number}}
    </p>
{% endif %}  
{% endfor %}
 -->





<div class="container my-5">
    <div class="row">
        <div class="col-md-5">
            <div class="main-img">
                <img class="img-fluid" src="{{qs.first_image.image.url}}" alt="ProductS">
                <div class="row my-3 previews">
                    {% for item in qs.all_image_related %}
                    <div class="col-md-3">
                        <img class="w-100" src="{{item.image.url}}" alt="Sale">   
                    </div>
                    {% endfor %}
                </div>
                
            </div>
        </div>
        <div class="col-md-7">
            <div class="main-description px-2">
                <div class="category text-bold">
                    Category: {{qs.category}}
                </div>
                <div class="product-title text-bold my-3">
                    {{qs.brand}}
                </div>


                <div class="price-area my-4">
                    <p class="old-price mb-1"><del>${{qs.price}}</del> <span class="old-price-discount text-danger">({{qs.discound}}% off)</span></p>
                    <p class="new-price text-bold mb-1">${{qs.new_price_after_discound}}</p>
                    <p class="text-secondary mb-1">(Additional tax may apply on checkout)</p>

                </div>


                <div class="buttons d-flex my-5">

                    <form action="{% url 'items:add_to_cart' %}" method="post">
                        {% csrf_token %}
                        <select  class="form-select"  aria-label="Default select example">
                            {% for item in product %}
                            {% if item.color %}
                            <option class="mb-3" value="{{item.pk}}">{{item.color}} </option>
                            {% endif %}  
                            {% endfor %}
                          </select>

                        <input type="hidden" name="product_id" value="{{qs.id}}">
                        <div class="block">
                            <button class="shadow btn custom-btn">Add to cart</button>
                        </div>
                    </form>

                </div>




            </div>

            <div class="product-details my-4">
                <p class="details-title text-color mb-1">Product Details</p>
                <p class="description">{{qs.description}}</p>
            </div>
          
                     <div class="row questions bg-light p-3">
                <div class="col-md-1 icon">
                    <i class="fa-brands fa-rocketchat questions-icon"></i>
                </div>
                <div class="col-md-11 text">
                    Have a question about our products at E-Store? Feel free to contact our representatives via live chat or email.
                </div>
            </div>

            <div class="delivery my-4">
                <p class="font-weight-bold mb-0"><span><i class="fa-solid fa-truck"></i></span> <b>Delivery done in 3 days from date of purchase</b> </p>
                <p class="text-secondary">Order now to get this product delivery</p>
            </div>
            <div class="delivery-options my-4">
                <p class="font-weight-bold mb-0"><span><i class="fa-solid fa-filter"></i></span> <b>Delivery options</b> </p>
                <p class="text-secondary">View delivery options here</p>
            </div>
            
         
        </div>
    </div>
</div>



<div class="container similar-products my-4">
    <hr>
    <p class="display-5">Similar Products Brand</p>

    <div class="row">
        
        {% for item in s_brand %}
        {% if item.all_image_related %}
        <div class="col-md-3">
            <div class="similar-product">
                <img class="w-100" src="{{item.first_image.image.url}}" alt="Preview">
                <p class="title">{{item.name}}</p>
                <p class="price">${{item.new_price_after_discound}}</p>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

<div class="container similar-products my-4">
    <hr>
    <p class="display-5">Similar Products Categories</p>

    <div class="row">
        
        {% for item in s_category %}
        {% if item.all_image_related %}
        <div class="col-md-3">
            <div class="similar-product">
                <img class="w-100" src="{{item.first_image.image.url}}" alt="Preview">
                <p class="title">{{item.name}}</p>
                <p class="price">${{item.new_price_after_discound}}</p>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>


</div>



         
 
{% endblock content %}
    

products/templates/products/home.html
{% extends 'base.html' %}


{% block title %}
    home
{% endblock title %}
    


{% block content %}
    
    <div class="container mt-5">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for item in qs %}
            {% if item.all_image_related %}
            <div class="col">
                <div class="card">
                  <a href="{{item.detail_product_url}}"><img src="{{item.first_image.image.url}}" class="card-img-top" alt="{{item.name}}"></a>
                  <div class="card-body">
                    <h5 class="card-title">{{item.name}}</h5>
                    <p class="card-text">
                        
                        {% if item.discound %}
                            <del>{{item.price}}</del> <span>{{item.new_price_after_discound}}</span>
                        {% else %}
                        {{item.new_price_after_discound}}
                        {% endif %}
                    </p>
                    
                  </div>
                </div>
              </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
        
{% endblock content %}
    

products/templates/products/images.html
{% extends 'base.html' %}


{% block title %}
    upload image
{% endblock title %}
    


{% block content %}
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">save</button>
        </form>
    </div>
{% endblock content %}
    

products/templates/products/manager.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    manager
{% endblock title %}
    


{% block content %}
    <div class="container mt-5">

        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for item in object.all_image_related %}
            <div class="col">
                <div class="card">
                    <p>
                        <a href="{{item.delete_image_url}}">delete</a>
                    </p>
                  <img src="{{item.image.url}}" class="card-img-top" alt="...">
                </div>
            </div>
            {% endfor %}
        </div>
        <form  class='space-y-5' method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div>
            {{ form.as_p }}
            </div>
        
            <div>
                {{ formset.management_form }}
                <div class="pb-3 border-b space-y-3" id="attachments">
                    {% for form in formset %}
                    <div>
                        {{ form.as_p }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        
            <button class="btn-submit mt-2" id="add-attachment-btn">Add attachment</button>
            <button type="submit" class="btn-submit mt-2">Save</button>
        </form>  
        <div class="hide"  id="blank-form">
            {{ formset.empty_form }}
        </div>
    </div>
   
{% endblock content %}


{% block script %}
        <script src="{% static 'action/atachments.js' %}" defer></script>
{% endblock script %}

products/templates/products/not-found.html
<!--
VIEW IN FULL SCREEN MODE
FULL SCREEN MODE: http://salehriaz.com/404Page/404.html

DRIBBBLE: https://dribbble.com/shots/4330167-404-Page-Lost-In-Space
-->

<body class="bg-purple">
        
    <div class="stars">
        <div class="custom-navbar">
            <div class="brand-logo">
                <img src="http://salehriaz.com/404Page/img/logo.svg" width="80px">
            </div>
            <div class="navbar-links">
                <ul>
                  <li><a href="http://salehriaz.com/404Page/404.html" target="_blank">Home</a></li>
                  <li><a href="http://salehriaz.com/404Page/404.html" target="_blank">About</a></li>
                  <li><a href="http://salehriaz.com/404Page/404.html" target="_blank">Features</a></li>
                  <li><a href="http://salehriaz.com/404Page/404.html" class="btn-request" target="_blank">Request A Demo</a></li>
                </ul>
            </div>
        </div>
        <div class="central-body">
            <img class="image-404" src="http://salehriaz.com/404Page/img/404.svg" width="300px">
            <a href="http://salehriaz.com/404Page/404.html" class="btn-go-home" target="_blank">GO BACK HOME</a>
        </div>
        <div class="objects">
            <img class="object_rocket" src="http://salehriaz.com/404Page/img/rocket.svg" width="40px">
            <div class="earth-moon">
                <img class="object_earth" src="http://salehriaz.com/404Page/img/earth.svg" width="100px">
                <img class="object_moon" src="http://salehriaz.com/404Page/img/moon.svg" width="80px">
            </div>
            <div class="box_astronaut">
                <img class="object_astronaut" src="http://salehriaz.com/404Page/img/astronaut.svg" width="140px">
            </div>
        </div>
        <div class="glowing_stars">
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>

        </div>

    </div>

</body>